import {
  Injectable,
  NotFoundException,
  BadRequestException,
  Logger,
} from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository, DataSource } from "typeorm";
import { JwtService } from "@nestjs/jwt";
import { ConfigService } from "@nestjs/config";
import ms from "ms";
import bcrypt from "bcryptjs";
import { IFitterRepository } from "./domain/fitter.repository";
import { Fitter } from "./domain/fitter";
import { UserEntity } from "../users/infrastructure/persistence/relational/entities/user.entity";
import { CreateFitterDto } from "./dto/create-fitter.dto";
import { UpdateFitterDto } from "./dto/update-fitter.dto";
import { FitterDto } from "./dto/fitter.dto";
import { MailService } from "../mail/mail.service";
import { AllConfigType } from "../config/config.type";

/**
 * Fitter Application Service
 *
 * Orchestrates fitter domain operations.
 * Uses domain repository abstraction for fitter data access.
 * Retains direct UserEntity access for cross-entity password updates.
 */
@Injectable()
export class FitterService {
  private readonly logger = new Logger(FitterService.name);

  constructor(
    private readonly fitterRepository: IFitterRepository,
    @InjectRepository(UserEntity)
    private readonly userRepository: Repository<UserEntity>,
    private readonly dataSource: DataSource,
    private readonly mailService: MailService,
    private readonly jwtService: JwtService,
    private readonly configService: ConfigService<AllConfigType>,
  ) {}

  async create(createFitterDto: CreateFitterDto): Promise<FitterDto> {
    let userId: number | null = createFitterDto.userId ?? null;

    // Create a user account if username and password are provided
    if (createFitterDto.username && createFitterDto.password) {
      try {
        // Check if username already exists
        const existingUser = await this.userRepository.findOne({
          where: { username: createFitterDto.username },
        });
        if (existingUser) {
          throw new BadRequestException("Username already exists");
        }

        // Hash the password
        const salt = await bcrypt.genSalt();
        const hashedPassword = await bcrypt.hash(
          createFitterDto.password,
          salt,
        );

        // Build the display name
        const displayName =
          [createFitterDto.firstName, createFitterDto.lastName]
            .filter(Boolean)
            .join(" ") || createFitterDto.username;

        // Insert directly into the credentials table
        // (the "user" entity is a VIEW on credentials, INSERTs must go to the base table)
        const result = await this.dataSource.query(
          `INSERT INTO credentials (
            deleted, user_type, user_name, full_name, password_hash,
            last_login, blocked, password_reset_hash, password_reset_valid_to, supervisor
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
          RETURNING user_id`,
          [
            0, // deleted
            1, // user_type = fitter
            createFitterDto.username,
            displayName,
            hashedPassword,
            0, // last_login (unix timestamp)
            0, // blocked = not blocked
            "", // password_reset_hash
            0, // password_reset_valid_to
            0, // supervisor = no
          ],
        );

        userId = result[0]?.user_id ?? null;
        this.logger.log(
          `Created credentials for "${createFitterDto.username}" with user_id ${userId}`,
        );
      } catch (error) {
        if (error instanceof BadRequestException) {
          throw error;
        }
        this.logger.error(`Failed to create user account: ${error.message}`);
        throw new BadRequestException(
          `Failed to create user account: ${error.message}`,
        );
      }
    }

    // user_id is NOT NULL in the database, so a user account must exist
    if (userId === null) {
      throw new BadRequestException(
        "A username and password are required to create a fitter account",
      );
    }

    // Create the fitter with NOT NULL-safe defaults
    const fitter = Fitter.create(
      0, // Auto-generated by database
      userId,
      createFitterDto.address ?? "",
      createFitterDto.zipcode ?? "",
      createFitterDto.state ?? "",
      createFitterDto.city ?? "",
      createFitterDto.country ?? "",
      createFitterDto.phoneNo ?? "",
      createFitterDto.cellNo ?? "",
      createFitterDto.currency ?? 1,
      createFitterDto.emailaddress ?? "",
    );

    const savedFitter = await this.fitterRepository.save(fitter);

    // Send welcome email with password reset link
    const fitterEmail = createFitterDto.emailaddress;
    if (fitterEmail && userId) {
      try {
        const tokenExpiresIn = this.configService.getOrThrow(
          "auth.forgotExpires",
          { infer: true },
        );
        const tokenExpires = Date.now() + ms(tokenExpiresIn);

        // Find the user's UUID to create a proper reset token
        const userRecord = await this.dataSource.query(
          `SELECT id FROM "user" WHERE legacy_id = $1 LIMIT 1`,
          [userId],
        );
        const userUuid = userRecord[0]?.id;

        if (userUuid) {
          const hash = await this.jwtService.signAsync(
            { forgotUserId: userUuid },
            {
              secret: this.configService.getOrThrow("auth.forgotSecret", {
                infer: true,
              }),
              expiresIn: tokenExpiresIn,
            },
          );

          await this.mailService.welcomeFitter({
            to: fitterEmail,
            data: { hash, tokenExpires },
          });

          this.logger.log(
            `Welcome email sent to fitter "${createFitterDto.username}" at ${fitterEmail}`,
          );
        }
      } catch (error) {
        // Don't fail fitter creation if email sending fails
        this.logger.error(
          `Failed to send welcome email to ${fitterEmail}: ${error.message}`,
        );
      }
    }

    return this.toDto(savedFitter);
  }

  async findOne(id: number): Promise<FitterDto> {
    const fitter = await this.fitterRepository.findById(id);
    if (!fitter) {
      throw new NotFoundException("Fitter not found");
    }
    return this.toDto(fitter);
  }

  async findAll(
    page: number = 1,
    limit: number = 10,
    city?: string,
    country?: string,
    searchTerm?: string,
    name?: string,
    username?: string,
    status?: string,
  ): Promise<{ data: FitterDto[]; total: number; pages: number }> {
    const { fitters, total } = await this.fitterRepository.findAllPaginated({
      page,
      limit,
      city,
      country,
      searchTerm,
      name,
      username,
      status,
    });

    const dtos = fitters.map((fitter) => this.toDto(fitter));

    // Supplement DTOs with user data (name, username, enabled, lastLogin)
    const userIds = dtos
      .map((d) => d.userId)
      .filter((uid): uid is number => uid !== undefined && uid !== null);

    if (userIds.length > 0) {
      const users = await this.dataSource.query(
        `SELECT legacy_id, name, username, enabled, last_login FROM "user" WHERE legacy_id = ANY($1::int[])`,
        [userIds],
      );
      const userMap = new Map<number, Record<string, unknown>>();
      for (const u of users) {
        userMap.set(u.legacy_id, u);
      }
      for (const dto of dtos) {
        const user = dto.userId ? userMap.get(dto.userId) : undefined;
        if (user) {
          dto.name = user.name as string;
          dto.username = user.username as string;
          dto.enabled = user.enabled as boolean;
          dto.lastLogin = user.last_login as Date;
        }
      }
    }

    return {
      data: dtos,
      total,
      pages: Math.ceil(total / limit),
    };
  }

  async update(
    id: number,
    updateFitterDto: UpdateFitterDto,
  ): Promise<FitterDto> {
    const fitter = await this.fitterRepository.findById(id);
    if (!fitter) {
      throw new NotFoundException("Fitter not found");
    }

    fitter.updateInfo(
      updateFitterDto.userId,
      updateFitterDto.address,
      updateFitterDto.zipcode,
      updateFitterDto.state,
      updateFitterDto.city,
      updateFitterDto.country,
      updateFitterDto.phoneNo,
      updateFitterDto.cellNo,
      updateFitterDto.currency,
      updateFitterDto.emailaddress,
    );

    // Update the linked user's password if provided
    // "user" is a VIEW on the credentials table, so update credentials directly
    if (updateFitterDto.password && fitter.userId) {
      const salt = await bcrypt.genSalt();
      const hashedPassword = await bcrypt.hash(updateFitterDto.password, salt);
      await this.dataSource.query(
        `UPDATE credentials SET password_hash = $1 WHERE user_id = $2`,
        [hashedPassword, fitter.userId],
      );
    }

    // Persist firstName/lastName back to credentials.full_name (the legacy schema
    // has no separate first/last columns). Skip when both come in empty so we
    // don't blank an existing name.
    if (
      (updateFitterDto.firstName !== undefined ||
        updateFitterDto.lastName !== undefined) &&
      fitter.userId
    ) {
      const newFullName = [updateFitterDto.firstName, updateFitterDto.lastName]
        .filter((part): part is string => !!part && part.trim().length > 0)
        .join(" ")
        .trim();
      if (newFullName) {
        await this.dataSource.query(
          `UPDATE credentials SET full_name = $1 WHERE user_id = $2`,
          [newFullName, fitter.userId],
        );
      }
    }

    const savedFitter = await this.fitterRepository.save(fitter);
    return this.toDto(savedFitter);
  }

  async remove(id: number): Promise<void> {
    const fitter = await this.fitterRepository.findById(id);
    if (!fitter) {
      throw new NotFoundException("Fitter not found");
    }
    await this.fitterRepository.softDelete(id);
  }

  async findByUserId(userId: number): Promise<FitterDto | null> {
    const fitter = await this.fitterRepository.findByUserId(userId);
    return fitter ? this.toDto(fitter) : null;
  }

  async findDistinctCountries(): Promise<string[]> {
    return this.fitterRepository.findDistinctCountries();
  }

  async findActiveFitters(): Promise<FitterDto[]> {
    const fitters = await this.fitterRepository.findActive();
    return fitters.map((fitter) => this.toDto(fitter));
  }

  async findByCountry(country: string): Promise<FitterDto[]> {
    const fitters = await this.fitterRepository.findByCountry(country);
    return fitters.map((fitter) => this.toDto(fitter));
  }

  async findByCity(city: string): Promise<FitterDto[]> {
    const fitters = await this.fitterRepository.findByCity(city);
    return fitters.map((fitter) => this.toDto(fitter));
  }

  async getCountByCountry(country: string): Promise<number> {
    return this.fitterRepository.countByCountry(country);
  }

  async getActiveCount(): Promise<number> {
    return this.fitterRepository.countActive();
  }

  /**
   * Toggle block status for a fitter user.
   * Flips the `blocked` column in the credentials table.
   */
  async toggleBlock(id: number): Promise<{ enabled: boolean }> {
    const fitter = await this.fitterRepository.findById(id);
    if (!fitter) {
      throw new NotFoundException("Fitter not found");
    }

    if (!fitter.userId) {
      throw new NotFoundException("Fitter has no linked user account");
    }

    // Toggle blocked in credentials table
    await this.dataSource.query(
      `UPDATE credentials SET blocked = CASE WHEN blocked = 0 THEN 1 ELSE 0 END WHERE user_id = $1`,
      [fitter.userId],
    );

    const result = await this.dataSource.query(
      `SELECT blocked FROM credentials WHERE user_id = $1`,
      [fitter.userId],
    );

    return { enabled: result[0]?.blocked === 0 };
  }

  private toDto(fitter: Fitter): FitterDto {
    const dto = new FitterDto();
    dto.id = fitter.id;
    dto.userId = fitter.userId ?? undefined;
    dto.address = fitter.address ?? undefined;
    dto.zipcode = fitter.zipcode ?? undefined;
    dto.state = fitter.state ?? undefined;
    dto.city = fitter.city ?? undefined;
    dto.country = fitter.country ?? undefined;
    dto.phoneNo = fitter.phoneNo ?? undefined;
    dto.cellNo = fitter.cellNo ?? undefined;
    dto.currency = fitter.currency ?? undefined;
    dto.emailaddress = fitter.emailaddress ?? undefined;
    dto.deleted = fitter.deleted;
    dto.isActive = fitter.isActive();
    dto.fullAddress = fitter.getFullAddress();
    dto.displayName = fitter.getDisplayName();
    return dto;
  }
}
