import { Injectable, NotFoundException } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import bcrypt from "bcryptjs";
import { IFitterRepository } from "./domain/fitter.repository";
import { Fitter } from "./domain/fitter";
import { UserEntity } from "../users/infrastructure/persistence/relational/entities/user.entity";
import { CreateFitterDto } from "./dto/create-fitter.dto";
import { UpdateFitterDto } from "./dto/update-fitter.dto";
import { FitterDto } from "./dto/fitter.dto";

/**
 * Fitter Application Service
 *
 * Orchestrates fitter domain operations.
 * Uses domain repository abstraction for fitter data access.
 * Retains direct UserEntity access for cross-entity password updates.
 */
@Injectable()
export class FitterService {
  constructor(
    private readonly fitterRepository: IFitterRepository,
    @InjectRepository(UserEntity)
    private readonly userRepository: Repository<UserEntity>,
  ) {}

  async create(createFitterDto: CreateFitterDto): Promise<FitterDto> {
    const fitter = Fitter.create(
      0, // Auto-generated by database
      createFitterDto.userId ?? null,
      createFitterDto.address ?? null,
      createFitterDto.zipcode ?? null,
      createFitterDto.state ?? null,
      createFitterDto.city ?? null,
      createFitterDto.country ?? null,
      createFitterDto.phoneNo ?? null,
      createFitterDto.cellNo ?? null,
      createFitterDto.currency ?? null,
      createFitterDto.emailaddress ?? null,
    );

    const savedFitter = await this.fitterRepository.save(fitter);
    return this.toDto(savedFitter);
  }

  async findOne(id: number): Promise<FitterDto> {
    const fitter = await this.fitterRepository.findById(id);
    if (!fitter) {
      throw new NotFoundException("Fitter not found");
    }
    return this.toDto(fitter);
  }

  async findAll(
    page: number = 1,
    limit: number = 10,
    city?: string,
    country?: string,
  ): Promise<{ data: FitterDto[]; total: number; pages: number }> {
    const { fitters, total } = await this.fitterRepository.findAllPaginated({
      page,
      limit,
      city,
      country,
    });

    return {
      data: fitters.map((fitter) => this.toDto(fitter)),
      total,
      pages: Math.ceil(total / limit),
    };
  }

  async update(
    id: number,
    updateFitterDto: UpdateFitterDto,
  ): Promise<FitterDto> {
    const fitter = await this.fitterRepository.findById(id);
    if (!fitter) {
      throw new NotFoundException("Fitter not found");
    }

    fitter.updateInfo(
      updateFitterDto.userId,
      updateFitterDto.address,
      updateFitterDto.zipcode,
      updateFitterDto.state,
      updateFitterDto.city,
      updateFitterDto.country,
      updateFitterDto.phoneNo,
      updateFitterDto.cellNo,
      updateFitterDto.currency,
      updateFitterDto.emailaddress,
    );

    // Update the linked user's password if provided
    if (updateFitterDto.password && fitter.userId) {
      const user = await this.userRepository.findOne({
        where: { legacyId: fitter.userId },
      });
      if (user) {
        const salt = await bcrypt.genSalt();
        user.password = await bcrypt.hash(updateFitterDto.password, salt);
        await this.userRepository.save(user);
      }
    }

    const savedFitter = await this.fitterRepository.save(fitter);
    return this.toDto(savedFitter);
  }

  async remove(id: number): Promise<void> {
    const fitter = await this.fitterRepository.findById(id);
    if (!fitter) {
      throw new NotFoundException("Fitter not found");
    }
    await this.fitterRepository.softDelete(id);
  }

  async findByUserId(userId: number): Promise<FitterDto | null> {
    const fitter = await this.fitterRepository.findByUserId(userId);
    return fitter ? this.toDto(fitter) : null;
  }

  async findActiveFitters(): Promise<FitterDto[]> {
    const fitters = await this.fitterRepository.findActive();
    return fitters.map((fitter) => this.toDto(fitter));
  }

  async findByCountry(country: string): Promise<FitterDto[]> {
    const fitters = await this.fitterRepository.findByCountry(country);
    return fitters.map((fitter) => this.toDto(fitter));
  }

  async findByCity(city: string): Promise<FitterDto[]> {
    const fitters = await this.fitterRepository.findByCity(city);
    return fitters.map((fitter) => this.toDto(fitter));
  }

  async getCountByCountry(country: string): Promise<number> {
    return this.fitterRepository.countByCountry(country);
  }

  async getActiveCount(): Promise<number> {
    return this.fitterRepository.countActive();
  }

  private toDto(fitter: Fitter): FitterDto {
    const dto = new FitterDto();
    dto.id = fitter.id;
    dto.userId = fitter.userId ?? undefined;
    dto.address = fitter.address ?? undefined;
    dto.zipcode = fitter.zipcode ?? undefined;
    dto.state = fitter.state ?? undefined;
    dto.city = fitter.city ?? undefined;
    dto.country = fitter.country ?? undefined;
    dto.phoneNo = fitter.phoneNo ?? undefined;
    dto.cellNo = fitter.cellNo ?? undefined;
    dto.currency = fitter.currency ?? undefined;
    dto.emailaddress = fitter.emailaddress ?? undefined;
    dto.deleted = fitter.deleted;
    dto.isActive = fitter.isActive();
    dto.fullAddress = fitter.getFullAddress();
    dto.displayName = fitter.getDisplayName();
    return dto;
  }
}
