import { fetchEntities } from './api';
import { API_URL } from './api-config';
import { logger } from '@/utils/logger';

export interface Extra {
  id: number;
  name: string;
  type?: number;
  sequence?: number;
  active?: boolean;
  isActive?: boolean;
  deleted?: number;
  extraAllowed?: boolean;
  price1?: number;
  price2?: number;
  price3?: number;
  price4?: number;
  price5?: number;
  price6?: number;
  price7?: number;
  priceContrast1?: number;
  priceContrast2?: number;
  priceContrast3?: number;
  priceContrast4?: number;
  priceContrast5?: number;
  priceContrast6?: number;
  priceContrast7?: number;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface ExtrasResponse {
  'hydra:member': Extra[];
  'hydra:totalItems': number;
  'hydra:view'?: {
    '@id': string;
    'hydra:first'?: string;
    'hydra:last'?: string;
    'hydra:next'?: string;
    'hydra:previous'?: string;
  };
}

export async function fetchExtras({
  page = 1,
  searchTerm = '',
  filters = {},
  orderBy = 'sequence',
  order = 'asc'
}: {
  page?: number;
  searchTerm?: string;
  filters?: Record<string, string>;
  orderBy?: string;
  order?: 'asc' | 'desc';
} = {}): Promise<ExtrasResponse> {
  logger.log('fetchExtras: Called with params:', { page, searchTerm, filters, orderBy, order });

  // Build filter parameters — query options table with type=2 (extras)
  const extraParams: Record<string, string | number | boolean> = {
    type: 2,
  };

  // Handle individual field filters
  Object.entries(filters).forEach(([key, value]) => {
    if (value && value.trim()) {
      logger.log(`fetchExtras: Processing filter ${key}:`, value);
      if (key === 'name') {
        extraParams['name[contains]'] = value;
      } else if (key === 'description') {
        extraParams['description[contains]'] = value;
      } else if (key === 'active') {
        extraParams['active'] = value === 'true';
      } else if (key === 'sequence') {
        extraParams['sequence'] = parseInt(value);
      } else {
        extraParams[key] = value;
      }
    }
  });

  logger.log('fetchExtras: Calling fetchEntities with entity "options" (type=2) and params:', extraParams);

  return await fetchEntities({
    entity: 'options',
    page,
    partial: false,
    searchTerm,
    orderBy,
    order,
    extraParams
  });
}

export async function createExtra(extraData: Partial<Extra>): Promise<Extra> {
  // Use BreezeJS save bundle (matching options.ts pattern)
  const entity = {
    name: extraData.name,
    type: 2, // Extras are options with type=2
    sequence: extraData.sequence || 0,
    price1: extraData.price1 ?? 0,
    price2: extraData.price2 ?? 0,
    price3: extraData.price3 ?? 0,
    price4: extraData.price4 ?? 0,
    price5: extraData.price5 ?? 0,
    price6: extraData.price6 ?? 0,
    price7: extraData.price7 ?? 0,
    entityAspect: {
      entityTypeName: "Option:#App.Entity.Modelling",
      entityState: "Added",
      originalValuesMap: {},
      autoGeneratedKey: null,
      defaultResourceName: "options"
    }
  };

  const saveBundle = { entities: [entity] };

  logger.log('Attempting extra creation with BreezeJS SaveBundle:', JSON.stringify(saveBundle, null, 2));

  const response = await fetch(`${API_URL}/save`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/ld+json',
      'Accept': 'application/ld+json',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
    },
    credentials: 'include',
    body: JSON.stringify(saveBundle),
  });

  if (!response.ok) {
    const errorText = await response.text();
    logger.error('Extra creation failed:', errorText);
    throw new Error(`Failed to create extra: ${response.statusText}`);
  }

  const result = await response.json();
  logger.log('Extra creation result:', result);

  return result.Entities?.[0] || result.entities?.[0] || result;
}

export async function updateExtra(id: number, extraData: Partial<Extra>): Promise<Extra> {
  // Use BreezeJS save bundle (matching options.ts pattern)
  const entity: Record<string, unknown> = {
    id: id,
    type: 2, // Ensure type stays as extras
    entityAspect: {
      entityTypeName: "Option:#App.Entity.Modelling",
      entityState: "Modified",
      originalValuesMap: {},
      autoGeneratedKey: null,
      defaultResourceName: "options"
    }
  };

  if (extraData.name !== undefined) entity.name = extraData.name;
  if (extraData.sequence !== undefined) entity.sequence = extraData.sequence;
  if (extraData.price1 !== undefined) entity.price1 = extraData.price1;
  if (extraData.price2 !== undefined) entity.price2 = extraData.price2;
  if (extraData.price3 !== undefined) entity.price3 = extraData.price3;
  if (extraData.price4 !== undefined) entity.price4 = extraData.price4;
  if (extraData.price5 !== undefined) entity.price5 = extraData.price5;
  if (extraData.price6 !== undefined) entity.price6 = extraData.price6;
  if (extraData.price7 !== undefined) entity.price7 = extraData.price7;

  const saveBundle = { entities: [entity] };

  logger.log('Attempting extra update with BreezeJS SaveBundle:', JSON.stringify(saveBundle, null, 2));

  const response = await fetch(`${API_URL}/save`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/ld+json',
      'Accept': 'application/ld+json',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
    },
    credentials: 'include',
    body: JSON.stringify(saveBundle),
  });

  if (!response.ok) {
    const errorText = await response.text();
    logger.error('Extra update failed:', errorText);
    throw new Error(`Failed to update extra: ${response.statusText}`);
  }

  const result = await response.json();
  logger.log('Extra update result:', result);

  return result.Entities?.[0] || result.entities?.[0] || result;
}

export async function deleteExtra(id: number): Promise<void> {
  const response = await fetch(`${API_URL}/options/${id}`, {
    method: 'DELETE',
    headers: { 'Accept': 'application/json' },
    credentials: 'include',
  });

  if (!response.ok) {
    throw new Error(`Failed to delete extra: ${response.statusText}`);
  }
}
