import { Injectable, Logger } from "@nestjs/common";
import { DataSource } from "typeorm";

/**
 * Order seed data using the legacy database schema column names.
 *
 * Legacy orders table columns (from InitialSchema migration):
 *   id, fitter_id, saddle_id, leather_id, factory_id, fitter_stock,
 *   customer_id, name, order_status, order_time, payment, price_saddle,
 *   price_tradein, price_deposit, price_discount, price_fittingeval,
 *   price_callfee, price_girth, price_shipping, price_tax, price_additional,
 *   special_notes, serial_number, custom_order, changed, repair, demo,
 *   sponsored, rushed, currency, order_data, seat_sizes, ...
 *
 * Boolean flags (rushed, repair, demo, sponsored, custom_order) are
 * converted to boolean type by the AddLegacyBooleanFieldsToOrders migration.
 */
const ORDERS = [
  // Orders 1-3: New orders (order_status=0)
  {
    id: 1,
    fitterId: 1,
    factoryId: 3,
    customerId: 1,
    saddleId: 1,
    leatherId: 1,
    orderStatus: 0,
    orderTime: 1700000000,
    priceSaddle: 350000,
    priceDeposit: 100000,
    priceShipping: 7500,
    specialNotes: "Standard fitting for dressage horse",
    currency: 2,
    rushed: false,
    repair: false,
    demo: false,
    customOrder: false,
    seatSizes: '["17"]',
  },
  {
    id: 2,
    fitterId: 2,
    factoryId: 2,
    customerId: 3,
    saddleId: 3,
    leatherId: 3,
    orderStatus: 0,
    orderTime: 1700100000,
    priceSaddle: 420000,
    priceDeposit: 120000,
    priceShipping: 10000,
    specialNotes: "",
    currency: 3,
    rushed: false,
    repair: false,
    demo: false,
    customOrder: false,
    seatSizes: '["17,5"]',
  },
  {
    id: 3,
    fitterId: 3,
    factoryId: 1,
    customerId: 5,
    saddleId: 2,
    leatherId: 5,
    orderStatus: 0,
    orderTime: 1700200000,
    priceSaddle: 380000,
    priceDeposit: 95000,
    priceShipping: 12000,
    specialNotes: "Wide tree preferred",
    currency: 1,
    rushed: false,
    repair: false,
    demo: false,
    customOrder: false,
    seatSizes: '["18"]',
  },
  // Orders 4-5: Confirmed (order_status=1)
  {
    id: 4,
    fitterId: 1,
    factoryId: 3,
    customerId: 2,
    saddleId: 4,
    leatherId: 2,
    orderStatus: 1,
    orderTime: 1699800000,
    priceSaddle: 450000,
    priceDeposit: 200000,
    priceShipping: 7500,
    specialNotes: "Needs extra knee roll padding",
    currency: 2,
    rushed: false,
    repair: false,
    demo: false,
    customOrder: false,
    seatSizes: '["17"]',
  },
  {
    id: 5,
    fitterId: 4,
    factoryId: 4,
    customerId: 7,
    saddleId: 1,
    leatherId: 7,
    orderStatus: 1,
    orderTime: 1699900000,
    priceSaddle: 320000,
    priceDeposit: 160000,
    priceShipping: 15000,
    specialNotes: "",
    currency: 4,
    rushed: false,
    repair: false,
    demo: false,
    customOrder: false,
    seatSizes: '["16,5"]',
  },
  // Orders 6-8: In production (order_status=3)
  {
    id: 6,
    fitterId: 2,
    factoryId: 2,
    customerId: 4,
    saddleId: 5,
    leatherId: 4,
    orderStatus: 3,
    orderTime: 1699500000,
    priceSaddle: 480000,
    priceDeposit: 240000,
    priceShipping: 10000,
    specialNotes: "Wolfgang Solo with extended panels",
    currency: 3,
    rushed: false,
    repair: false,
    demo: false,
    customOrder: false,
    seatSizes: '["17,5"]',
  },
  {
    id: 7,
    fitterId: 3,
    factoryId: 1,
    customerId: 6,
    saddleId: 6,
    leatherId: 6,
    orderStatus: 3,
    orderTime: 1699600000,
    priceSaddle: 500000,
    priceDeposit: 250000,
    priceShipping: 12000,
    specialNotes: "",
    currency: 1,
    rushed: false,
    repair: false,
    demo: false,
    customOrder: false,
    seatSizes: '["18"]',
  },
  {
    id: 8,
    fitterId: 5,
    factoryId: 3,
    customerId: 9,
    saddleId: 8,
    leatherId: 8,
    orderStatus: 3,
    orderTime: 1699700000,
    priceSaddle: 390000,
    priceDeposit: 195000,
    priceShipping: 15000,
    specialNotes: "Ship to Sydney warehouse",
    currency: 5,
    rushed: false,
    repair: false,
    demo: false,
    customOrder: false,
    seatSizes: '["17"]',
  },
  // Orders 9-11: Completed (order_status=7)
  {
    id: 9,
    fitterId: 1,
    factoryId: 3,
    customerId: 1,
    saddleId: 2,
    leatherId: 9,
    orderStatus: 7,
    orderTime: 1695000000,
    priceSaddle: 360000,
    priceDeposit: 360000,
    priceShipping: 7500,
    specialNotes: "Second saddle for client",
    currency: 2,
    rushed: false,
    repair: false,
    demo: false,
    customOrder: false,
    seatSizes: '["17,5"]',
  },
  {
    id: 10,
    fitterId: 2,
    factoryId: 2,
    customerId: 3,
    saddleId: 1,
    leatherId: 10,
    orderStatus: 7,
    orderTime: 1696000000,
    priceSaddle: 340000,
    priceDeposit: 340000,
    priceShipping: 10000,
    specialNotes: "",
    currency: 3,
    rushed: false,
    repair: false,
    demo: false,
    customOrder: false,
    seatSizes: '["16,5"]',
  },
  {
    id: 11,
    fitterId: 4,
    factoryId: 4,
    customerId: 8,
    saddleId: 3,
    leatherId: 1,
    orderStatus: 7,
    orderTime: 1697000000,
    priceSaddle: 410000,
    priceDeposit: 410000,
    priceShipping: 15000,
    specialNotes: "Gift wrapping requested",
    currency: 4,
    rushed: false,
    repair: false,
    demo: false,
    customOrder: false,
    seatSizes: '["18"]',
  },
  // Order 12: Cancelled (order_status=16)
  {
    id: 12,
    fitterId: 5,
    factoryId: 3,
    customerId: 9,
    saddleId: 4,
    leatherId: 2,
    orderStatus: 16,
    orderTime: 1700300000,
    priceSaddle: 430000,
    priceDeposit: 100000,
    priceShipping: 15000,
    specialNotes: "Cancelled by customer",
    currency: 5,
    rushed: false,
    repair: false,
    demo: false,
    customOrder: false,
    seatSizes: null,
  },
  // Order 13: Demo order
  {
    id: 13,
    fitterId: 3,
    factoryId: 1,
    customerId: 5,
    saddleId: 1,
    leatherId: 3,
    orderStatus: 0,
    orderTime: 1700400000,
    priceSaddle: 0,
    priceDeposit: 0,
    priceShipping: 0,
    specialNotes: "Demo saddle for trial period",
    currency: 1,
    rushed: false,
    repair: false,
    demo: true,
    customOrder: false,
    seatSizes: '["17"]',
  },
  // Order 14: Repair order
  {
    id: 14,
    fitterId: 2,
    factoryId: 2,
    customerId: 4,
    saddleId: 5,
    leatherId: 4,
    orderStatus: 1,
    orderTime: 1700500000,
    priceSaddle: 85000,
    priceDeposit: 42500,
    priceShipping: 10000,
    specialNotes: "Repair torn knee roll on left side",
    currency: 3,
    rushed: false,
    repair: true,
    demo: false,
    customOrder: false,
    seatSizes: null,
  },
  // Order 15: Rush custom order
  {
    id: 15,
    fitterId: 1,
    factoryId: 3,
    customerId: 2,
    saddleId: 8,
    leatherId: 7,
    orderStatus: 3,
    orderTime: 1700600000,
    priceSaddle: 550000,
    priceDeposit: 300000,
    priceShipping: 7500,
    specialNotes: "Rush custom build - competition deadline in 4 weeks",
    currency: 2,
    rushed: true,
    repair: false,
    demo: false,
    customOrder: true,
    seatSizes: '["17", "17,5"]',
  },
];

@Injectable()
export class OrderSeedService {
  private readonly logger = new Logger(OrderSeedService.name);

  constructor(private readonly dataSource: DataSource) {}

  async run(): Promise<void> {
    const nodeEnv = process.env.NODE_ENV;
    if (nodeEnv === "production") {
      this.logger.warn("Refusing to seed in production environment");
      return;
    }

    this.logger.log("Starting order seed...");

    for (const o of ORDERS) {
      await this.dataSource.query(
        `INSERT INTO orders (
          id, fitter_id, factory_id, customer_id, saddle_id, leather_id,
          order_status, order_time, price_saddle, price_deposit, price_shipping,
          special_notes, currency, rushed, repair, demo, custom_order,
          payment, order_data, price_tradein, price_discount,
          price_fittingeval, price_callfee, price_girth, price_tax,
          seat_sizes
        ) VALUES (
          $1, $2, $3, $4, $5, $6,
          $7, $8, $9, $10, $11,
          $12, $13, $14, $15, $16, $17,
          '', '', 0, 0,
          0, 0, 0, 0,
          $18
        ) ON CONFLICT (id) DO NOTHING`,
        [
          o.id,
          o.fitterId,
          o.factoryId,
          o.customerId,
          o.saddleId,
          o.leatherId,
          o.orderStatus,
          o.orderTime,
          o.priceSaddle,
          o.priceDeposit,
          o.priceShipping,
          o.specialNotes,
          o.currency,
          o.rushed,
          o.repair,
          o.demo,
          o.customOrder,
          o.seatSizes,
        ],
      );
    }

    this.logger.log("Order seed completed!");
  }
}
