apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: oms-frontend-pdb
  namespace: oms-nest-production
  labels:
    app: oms-frontend
    environment: production
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: oms-frontend
